---
version: '3'
tasks:
  pack:
    cmds:
      - |-
        pack build \
          doing-that-rag \
          --buildpack paketo-buildpacks/python \
          --builder paketobuildpacks/builder:base
  default:
    deps:
      - task: pack

